name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.15
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - protobuf=3.20.3
  - pandas
  - scikit-learn
  - pip:
      - mlflow==2.8.1
      - wandb==0.19.11
      - pytest
